version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./compose/postgres/.env
  web:
    build: ./compose/django
    env_file:
      - ./compose/django/.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./GusDelivery:/code
    ports:
      - "8000:8000"
    depends_on:
      - db