# Generated by Django 3.2.6 on 2021-08-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_nombre', models.CharField(max_length=255, verbose_name='nombre estandarizado')),
                ('d_asenta', models.CharField(max_length=255, verbose_name='nombre')),
                ('d_tipo_asenta', models.CharField(max_length=255, verbose_name='tipo')),
                ('c_tipo_asenta', models.CharField(max_length=255, verbose_name='tipo clave')),
                ('id_asenta_cpcons', models.CharField(max_length=255, verbose_name='id nivel municipal')),
                ('d_cp', models.CharField(max_length=255, verbose_name='cp administración')),
                ('d_oficina', models.CharField(max_length=255, verbose_name='cp oficina')),
                ('d_zona', models.CharField(max_length=255, verbose_name='zona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_nombre', models.CharField(max_length=255, verbose_name='nombre estandarizado')),
                ('d_estado', models.CharField(max_length=255, unique=True, verbose_name='nombre')),
                ('c_estado', models.CharField(max_length=255, unique=True, verbose_name='clave')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_nombre', models.CharField(max_length=255, verbose_name='nombre estandarizado')),
                ('d_mnpio', models.CharField(max_length=255, verbose_name='nombre')),
                ('c_mnpio', models.CharField(max_length=255, verbose_name='clave')),
                ('d_ciudad', models.CharField(blank=True, max_length=255, null=True, verbose_name='ciudad')),
                ('c_cve_ciudad', models.CharField(blank=True, max_length=255, null=True, verbose_name='ciudad clave')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_codigo', models.CharField(max_length=255, verbose_name='código postal')),
                ('d_asenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postal_codes.asentamiento', verbose_name='asentamiento')),
                ('d_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postal_codes.estado', verbose_name='estado')),
                ('d_mnpio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postal_codes.municipio', verbose_name='municipio')),
            ],
        ),
    ]
